### ISSUE TITLE
Ping

### ISSUE THREAD

**Issue by itay-grudev** [purism/warrant-canary#2]
Ping...

**Comment by toddatpurism** [comment]
From the last warrant canary issued on github:

https://github.com/purism/warrant-canary/blob/master/canaries/purism-warrant-canary-20180701.txt

> Warrant Canary, July 1st 2018
> 
> Effective July 1st, 2018 we are transitioning all warrant canaries to https://source.puri.sm as the definitive location for all future warrant canaries.
> 
> librem-hardware-warrant-canary-20180701.txt
> pureos-software-warrant-canary-20180701.txt
> purist-services-warrant-canary-20180701.txt

Please check https://puri.sm/warrant-canary/ for the latest

**Comment by itay-grudev** [comment]
Can you put it in the description / README and archive the repo?

**Comment by toddatpurism** [comment]
Sure, its been updated.
